### ISSUE TITLE
Problems in production online

### ISSUE THREAD

**Issue by marcostoduto** [olivmonnier/strapi-upload-dropbox#2]
Hi,
when I install your package and i set it up on my localhost there is no problem and it works perfectly, but If I deploy that on Heroku without setting it up on local: I open my cloud settings but I cannot see any other provider out of local server. 
I tried to set it up on local and then deploy it online already set up with my token, but I had the following issue:
```-----> Building dependencies
       Installing node modules (package.json + package-lock)
       npm ERR! path /tmp/build_5be66217e7860fb4df28d78b2e8ec138/node_modules/.staging/strapi-9a803903/node_modules/@babel/polyfill
       npm ERR! code ENOENT
       npm ERR! errno -2
       npm ERR! syscall rename
       npm ERR! enoent ENOENT: no such file or directory, rename '/tmp/build_5be66217e7860fb4df28d78b2e8ec138/node_modules/.staging/strapi-9a803903/node_modules/@babel/polyfill' -> '/tmp/build_5be66217e7860fb4df28d78b2e8ec138/node_modules/.staging/@babel/polyfill-9318cb13'
       npm ERR! enoent This is related to npm not being able to find a file.
       npm ERR! enoent 
       
       npm ERR! A complete log of this run can be found in:
       npm ERR!     /tmp/npmcache.N0vDH/_logs/2019-02-20T21_27_54_861Z-debug.log
```

Thank you so much for your help!

**Comment by olivmonnier** [comment]
Hi,
I'm not sure to understand your issue. This log indicate a temporary file missing associate to @babel/polyfill. Have you a public repository with this issue ?

**Comment by marcostoduto** [comment]
I solved it, I reinstalled strapi globally and now it works perfectly.

Thank you for your time
